### ISSUE TITLE
license server?

### ISSUE THREAD

**Issue by ghost** [superkhau/lice#9]
Hi.

I would like to know if you all have already thought about creating a lice server to be a license server. This question does context on adding an address of html files, projects and plugins.

**Comment by ralyodio** [comment]
What value would a license server provide?

**Comment by 78mF4n** [comment]
Hi ralyodio.

> What value would a license server provide?

1. There is a new networking protocol called nostr. So, there is a proposal in notr to validate, authenticate certain contents. It would be a great opportunity to have a license authentication server or even a "lice server" to authenticate certain contents, text licenses, etc.
2. There is a standardization called "web-components", in this standardization there is a proposal called "web-components-license" which should have a license server. This would be another opportunity to have a license server or a "lice server"

**Comment by rusteroobs** [comment]
> There is a new networking protocol called nostr. So, there is a proposal in nostr to validate, authenticate certain contents. It would be a great opportunity to have a license authentication server or even a "lice server" to authenticate certain contents, text licenses etc in nostr.

I think you meant this NIP here: [NIP IDEA: New note tag "content-licensed " (or label)](https://github.com/nostr-protocol/nips/issues/350)

**Comment by marcelolucario** [comment]
> There is a standardization called "web-components", in this standardization there is a proposal called "web-components-license" which should have a license server. This would be another opportunity to have a license server or a "lice server" for this.

This can be found in the officially html specification: [license-html](https://html.spec.whatwg.org/dev/links.html#link-type-license): *'the "license keyword" indicates that the referenced document provides the copyright license terms under which the main content of the current document is provided.'*

**Comment by ralyodio** [comment]
I love nostr, so if we can do this I'm infavor of it. I'm not sure what the server would actually do though...does it just host a copy of the licenses? Because we can use github for that.

**Comment by nichdemos** [comment]
Hi @ralyodio, how are you?

> I love nostr, so if we can do this I'm infavor of it. 

I don't know if I can help, but following some recent discussions in the nostr:nips protocol repository, there is a pull request about this here: [NIP-110: license tag](https://github.com/nostr-protocol/nips/pull/857). 

> I'm not sure what the server would actually do though...does it just host a copy of the licenses? Because we can use github for that.

**Please see this:** *"This NIP defines how to add an MIT license to Nostr events in order to protect relays and clients from potential legal responsibilities for distributing the copyright-protected content."*

It might be interesting to create a relay that filters nostr messages based on licensed content. The advantage of this initially is that each time the server filters, it could be paid privately or publicly funded to do so. Another advantage is that implementing a lice-relay version may not be that difficult.

***idea***
The illustrative image is based on this open project: [ufal/public-license-selector](https://ufal.github.io/public-license-selector/)
![image](https://github.com/superkhau/lice/assets/154566915/e684cb60-a3be-4490-8412-96340bc19dc0)

As we can see in the illustrative image we have a server called lice-relay which is the version of the lice software as a relay to filter messages from the nostr network by license type. The filtered messages are forwarded and forwarded in several specialized relay types for the licensed content. It's the same purpose as this project, but done on the nostr server side.

***What do you think of this idea? it makes sense?***
